import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homestay App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
    rel="stylesheet"
    href="https://unpkg.com/swiper/swiper-bundle.min.css"
  />
  {/* font awesome cdn link  */}
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  />
  {/* custom css file link  */}
  <link rel="stylesheet" href="style/style.css" />
  
      </Head>




      <main className={styles.main}>
      <header>
    <div id="menu-bar" className="fas fa-bars" />
    <a href="#" className="logo">
      <span>Home</span>Stay
    </a>
    <nav className="navbar">
      <a href="#home">home</a>
      <a href="#book">book</a>
      <a href="#packages">packages</a>
      <a href="#services">services</a>
      <a href="#gallery">gallery</a>
      <a href="#review">review</a>
      <a href="#contact">contact</a>
    </nav>
    <div className="icons">
      <i className="fas fa-search" id="search-btn" />
      <i className="fas fa-user" id="login-btn" />
    </div>
    <form action="" className="search-bar-container">
      <input type="search" id="search-bar" placeholder="search here..." />
      <label htmlFor="search-bar" className="fas fa-search" />
    </form>
  </header>
  {/* header section ends */}
  {/* login form container  */}
  <div className="login-form-container">
    <i className="fas fa-times" id="form-close" />
    <form action="">
      <h3>login</h3>
      <input type="email" className="box" placeholder="enter your email" />
      <input
        type="password"
        className="box"
        placeholder="enter your password"
      />
      <input type="submit" defaultValue="login now" className="btn" />
      <input type="checkbox" id="remember" />
      <label htmlFor="remember">remember me</label>
      <p>
        forget password? <a href="#">click here</a>
      </p>
      <p>
        don't have and account? <a href="#">register now</a>
      </p>
    </form>
  </div>
  {/* home section starts  */}
  <section className="home" id="home">
    <div className="content">
      <h3>adventure is worthwhile</h3>
      <p>dicover new places with us, adventure awaits</p>
      <a href="#" className="btn">
        discover more
      </a>
    </div>
    <div className="controls">
      <span className="vid-btn active" data-src="images/vid-1.mp4" />
      <span className="vid-btn" data-src="images/vid-2.mp4" />
      <span className="vid-btn" data-src="images/vid-3.mp4" />
      <span className="vid-btn" data-src="images/vid-4.mp4" />
      <span className="vid-btn" data-src="images/vid-5.mp4" />
    </div>
    <div className="video-container">
      <video
        src="images/vid-1.mp4"
        id="video-slider"
        loop=""
        autoPlay=""
        muted=""
      />
    </div>
  </section>
  {/* home section ends */}
  {/* book section starts  */}
  <section className="book" id="book">
    <h1 className="heading">
      <span>b</span>
      <span>o</span>
      <span>o</span>
      <span>k</span>
      <span className="space" />
      <span>n</span>
      <span>o</span>
      <span>w</span>
    </h1>
    <div className="row">
      <div className="image">
        <img src="images/book-img.svg" alt="" />
      </div>
      <form action="">
        <div className="inputBox">
          <h3>where to</h3>
          <input type="text" placeholder="place name" />
        </div>
        <div className="inputBox">
          <h3>how many</h3>
          <input type="number" placeholder="number of guests" />
        </div>
        <div className="inputBox">
          <h3>arrivals</h3>
          <input type="date" />
        </div>
        <div className="inputBox">
          <h3>leaving</h3>
          <input type="date" />
        </div>
        <input type="submit" className="btn" defaultValue="book now" />
      </form>
    </div>
  </section>
  {/* book section ends */}
  {/* packages section starts  */}
  <section className="packages" id="packages">
    <h1 className="heading">
      <span>p</span>
      <span>a</span>
      <span>c</span>
      <span>k</span>
      <span>a</span>
      <span>g</span>
      <span>e</span>
      <span>s</span>
    </h1>
    <div className="box-container">
      <div className="box">
        <img src="images/p-1.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> mumbai{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/p-2.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> hawaii{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/p-3.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> sydney{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/p-4.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> paris{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/p-5.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> tokyo{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/p-6.jpg" alt="" />
        <div className="content">
          <h3>
            {" "}
            <i className="fas fa-map-marker-alt" /> eypt{" "}
          </h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis,
            nam!
          </p>
          <div className="stars">
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="fas fa-star" />
            <i className="far fa-star" />
          </div>
          <div className="price">
            {" "}
            ₹501.00 <span>₹1001.00</span>{" "}
          </div>
          <a href="#" className="btn">
            book now
          </a>
        </div>
      </div>
    </div>
  </section>
  {/* packages section ends */}
  {/* services section starts  */}
  <section className="services" id="services">
    <h1 className="heading">
      <span>s</span>
      <span>e</span>
      <span>r</span>
      <span>v</span>
      <span>i</span>
      <span>c</span>
      <span>e</span>
      <span>s</span>
    </h1>
    <div className="box-container">
      <div className="box">
        <i className="fas fa-hotel" />
        <h3>affordable hotels</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
      <div className="box">
        <i className="fas fa-utensils" />
        <h3>food and drinks</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
      <div className="box">
        <i className="fas fa-bullhorn" />
        <h3>safty guide</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
      <div className="box">
        <i className="fas fa-globe-asia" />
        <h3>around the world</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
      <div className="box">
        <i className="fas fa-plane" />
        <h3>fastest travel</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
      <div className="box">
        <i className="fas fa-hiking" />
        <h3>adventures</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore
          commodi earum, quis voluptate exercitationem ut minima itaque iusto
          ipsum corrupti!
        </p>
      </div>
    </div>
  </section>
  {/* services section ends */}
  {/* gallery section starts  */}
  <section className="gallery" id="gallery">
    <h1 className="heading">
      <span>g</span>
      <span>a</span>
      <span>l</span>
      <span>l</span>
      <span>e</span>
      <span>r</span>
      <span>y</span>
    </h1>
    <div className="box-container">
      <div className="box">
        <img src="images/g-1.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-2.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-3.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-4.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-5.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-6.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-7.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-8.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
      <div className="box">
        <img src="images/g-9.jpg" alt="" />
        <div className="content">
          <h3>amazing places</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
            tenetur.
          </p>
          <a href="#" className="btn">
            see more
          </a>
        </div>
      </div>
    </div>
  </section>
  {/* gallery section ends */}
  {/* review section starts  */}
  <section className="review" id="review">
    <h1 className="heading">
      <span>r</span>
      <span>e</span>
      <span>v</span>
      <span>i</span>
      <span>e</span>
      <span>w</span>
    </h1>
    <div className="swiper-container review-slider">
      <div className="swiper-wrapper">
        <div className="swiper-slide">
          <div className="box">
            <img src="images/pic1.png" alt="" />
            <h3>Mrs Savita</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
              adipisci quisquam sunt nesciunt fugiat odit minus illum asperiores
              dolorum enim sint quod ipsam distinctio molestias consectetur
              ducimus beatae, reprehenderit exercitationem!
            </p>
            <div className="stars">
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="far fa-star" />
            </div>
          </div>
        </div>
        <div className="swiper-slide">
          <div className="box">
            <img src="images/pic2.png" alt="" />
            <h3>Mr raman</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
              adipisci quisquam sunt nesciunt fugiat odit minus illum asperiores
              dolorum enim sint quod ipsam distinctio molestias consectetur
              ducimus beatae, reprehenderit exercitationem!
            </p>
            <div className="stars">
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="far fa-star" />
            </div>
          </div>
        </div>
        <div className="swiper-slide">
          <div className="box">
            <img src="images/pic3.png" alt="" />
            <h3>Gyan_abhay</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
              adipisci quisquam sunt nesciunt fugiat odit minus illum asperiores
              dolorum enim sint quod ipsam distinctio molestias consectetur
              ducimus beatae, reprehenderit exercitationem!
            </p>
            <div className="stars">
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="far fa-star" />
            </div>
          </div>
        </div>
        <div className="swiper-slide">
          <div className="box">
            <img src="images/pic4.png" alt="" />
            <h3>Mr pawan</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
              adipisci quisquam sunt nesciunt fugiat odit minus illum asperiores
              dolorum enim sint quod ipsam distinctio molestias consectetur
              ducimus beatae, reprehenderit exercitationem!
            </p>
            <div className="stars">
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="fas fa-star" />
              <i className="far fa-star" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* review section ends */}
  {/* contact section starts  */}
  <section className="contact" id="contact">
    <h1 className="heading">
      <span>c</span>
      <span>o</span>
      <span>n</span>
      <span>t</span>
      <span>a</span>
      <span>c</span>
      <span>t</span>
    </h1>
    <div className="row">
      <div className="image">
        <img src="images/contact-img.svg" alt="" />
      </div>
      <form action="">
        <div className="inputBox">
          <input type="text" placeholder="name" />
          <input type="email" placeholder="email" />
        </div>
        <div className="inputBox">
          <input type="number" placeholder="number" />
          <input type="text" placeholder="subject" />
        </div>
        <textarea
          placeholder="message"
          name=""
          id=""
          cols={30}
          rows={10}
          defaultValue={""}
        />
        <input type="submit" className="btn" defaultValue="send message" />
      </form>
    </div>
  </section>
  {/* contact section ends */}
  {/* brand section  */}
  <section className="brand-container">
    <div className="swiper-container brand-slider">
      <div className="swiper-wrapper">
        <div className="swiper-slide">
          <img src="images/1.jpg" alt="" />
        </div>
        <div className="swiper-slide">
          <img src="images/2.jpg" alt="" />
        </div>
        <div className="swiper-slide">
          <img src="images/3.jpg" alt="" />
        </div>
        <div className="swiper-slide">
          <img src="images/4.jpg" alt="" />
        </div>
        <div className="swiper-slide">
          <img src="images/5.jpg" alt="" />
        </div>
        <div className="swiper-slide">
          <img src="images/6.jpg" alt="" />
        </div>
      </div>
    </div>
  </section>
  {/* footer section  */}
  <section className="footer">
    <div className="box-container">
      <div className="box">
        <h3>about us</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda
          quas magni pariatur est accusantium voluptas enim nemo facilis sit
          debitis.
        </p>
      </div>
      <div className="box">
        <h3>branch locations</h3>
        <a href="#">india</a>
        <a href="#">USA</a>
        <a href="#">japan</a>
        <a href="#">france</a>
      </div>
      <div className="box">
        <h3>quick links</h3>
        <a href="#">home</a>
        <a href="#">book</a>
        <a href="#">packages</a>
        <a href="#">services</a>
        <a href="#">gallery</a>
        <a href="#">review</a>
        <a href="#">contact</a>
      </div>
      <div className="box">
        <h3>follow us</h3>
        <a href="#">facebook</a>
        <a href="#">instagram</a>
        <a href="#">twitter</a>
        <a href="#">linkedin</a>
      </div>
    </div>
    <h1 className="credit">
      {" "}
      created by <span>Team_jaishreemahakal(Team_web_djsa) </span> | all rights
      reserved!{" "}
    </h1>
  </section>
  <Script src="https://unpkg.com/swiper/swiper-bundle.min.js"></Script>

  <Script src="script/script.js"></Script>
       







      </main>
    
     
    </div>
  )
}


export async function getStaticProps(context) {
  return {
    props: {},
  }
}
