import Head from "next/head";
import React from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Search from "../components/search";
import { useFirebase } from "../context/firebaseContext";
import HomeCarousel from "../components/homeCarousel";
import { Container } from "react-bootstrap";
import UtilityButtons from "../components/utilityButtons";
export default function Home() {
  const { getHomeHistory, UpdateStateHomestay } = useFirebase();
  // console.log(getHomeHistory);

  React.useEffect(() => {
    const update = async () => {
      await UpdateStateHomestay();
    };
    update();
  }, []);

  return (
    <Container className={styles.container}>
      <Head>
        <title>Homestay App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
          {/* <Search /> */}
      </Container>
      <div className={styles.herocontainer}>
        <div className={styles.hero}>
          <HomeCarousel />
        </div>
      </div>
      <Container className={styles.content}>
        <UtilityButtons />
        <Container className={styles.search}>
        </Container>
      </Container>
    </Container>
  );
}

export async function getStaticProps(context) {
  return {
    props: {},
  };
}
